Numpy Primer
============

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [3]:
np.zeros((2, 4, 3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [4]:
np.ones((2, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [5]:
np.ones((2, 4)) * 3

array([[ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.]])

In [6]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [7]:
np.random.randn(3, 4) # normal distributed values

array([[ 0.54895196, -0.47052757, -1.07685401, -1.13684172],
       [-0.74409138,  0.35783769, -0.94144043, -0.774503  ],
       [-0.73342063,  0.00822735,  1.08612156,  0.72404557]])

In [8]:
list(range(4))

[0, 1, 2, 3]

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
a = np.array([[1.0, 2.0], [5.0, 4.0]])
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [11]:
b = np.array([[4, 3], [2, 1]])
b

array([[4, 3],
       [2, 1]])

In [12]:
print(b.dtype, a.dtype) # each array has a data type (casting rules apply for int -> float)

int64 float64


In [13]:
v = np.array([0.5, 2.0])
v

array([ 0.5,  2. ])

In [14]:
np.array(["Mickey", "Mouse"]) # can hold more than just numbers

array(['Mickey', 'Mouse'],
      dtype='<U6')

In [15]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [16]:
a.diagonal()

array([ 1.,  4.])

In [17]:
np.transpose(a) 

array([[ 1.,  5.],
       [ 2.,  4.]])

In [18]:
a.T # shorthand

array([[ 1.,  5.],
       [ 2.,  4.]])

In [19]:
a.diagonal(1) # first diagonal

array([ 2.])

In [20]:
a.shape # returns a regular python tuple

(2, 2)

In [21]:
a.shape[0]

2

In [22]:
v.shape

(2,)

In [23]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [24]:
a[:, 0]

array([ 1.,  5.])

In [25]:
np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1) # reduce-operations reduce the whole array if no axis is specified

(12.0, array([ 6.,  6.]), array([ 3.,  9.]))

In [26]:
np.max(a, axis=1), np.mean(a, axis=0)

(array([ 2.,  5.]), array([ 3.,  3.]))

In [27]:
np.linalg.inv(a) 

array([[-0.66666667,  0.33333333],
       [ 0.83333333, -0.16666667]])

In [28]:
np.dot(a, b) # matrix multiplication

array([[  8.,   5.],
       [ 28.,  19.]])

In [29]:
a.dot(b) #shorthand : expects m x n matrix with a n x p matrix

array([[  8.,   5.],
       [ 28.,  19.]])

In [30]:
a.dot(np.linalg.inv(a)) # should be the identity matrix

array([[  1.00000000e+00,   0.00000000e+00],
       [ -4.44089210e-16,   1.00000000e+00]])

In [31]:
print(a)
print(b)

[[ 1.  2.]
 [ 5.  4.]]
[[4 3]
 [2 1]]


In [32]:
a * b # math operations are element-wise

array([[  4.,   6.],
       [ 10.,   4.]])

In [33]:
a - b

array([[-3., -1.],
       [ 3.,  3.]])

In [34]:
np.linalg.solve(a, v) # solves ax = v

array([ 0.33333333,  0.08333333])

In [35]:
np.reshape(a, (4,))

array([ 1.,  2.,  5.,  4.])

In [36]:
np.reshape(a, (4,)), np.ravel(a) # flattening

(array([ 1.,  2.,  5.,  4.]), array([ 1.,  2.,  5.,  4.]))

In [37]:
a.reshape((4, 1))

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [38]:
a.reshape((-1, 1)) # a[-1] means 'whatever needs to go there'

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [39]:
np.hstack([a, b])

array([[ 1.,  2.,  4.,  3.],
       [ 5.,  4.,  2.,  1.]])

In [40]:
np.vstack([a, b])

array([[ 1.,  2.],
       [ 5.,  4.],
       [ 4.,  3.],
       [ 2.,  1.]])

In [43]:
v.reshape([1,2])

array([[ 0.5,  2. ]])

In [44]:
np.vstack([a, b]) + v.reshape([1,2]) # broadcasting, assumes a (2,) vector is seen as a (1,2) vector

array([[ 1.5,  4. ],
       [ 5.5,  6. ],
       [ 4.5,  5. ],
       [ 2.5,  3. ]])

In [45]:
np.hstack([a, b]).shape

(2, 4)

In [46]:
np.hstack([a, b]) + v.reshape([2,1]) # does not work

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [47]:
np.hstack([a, b]) + v.T # transposing a 1-D array achieves nothing

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [48]:
np.hstack([a, b]) + v.reshape((-1, 1)) # reshaping to convert v from a (2,) vector to a (2,1) matrix

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [49]:
np.hstack([a, b]) + v[:, np.newaxis] # equivalently, we can add an axis

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [50]:
np.dstack([a, b, b , b]) # 

array([[[ 1.,  4.,  4.,  4.],
        [ 2.,  3.,  3.,  3.]],

       [[ 5.,  2.,  2.,  2.],
        [ 4.,  1.,  1.,  1.]]])

In [51]:
np.dstack([a, b, b, b]).shape

(2, 2, 4)

In [52]:
r = np.random.random_integers(0, 9, size=(3, 4))

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  """Entry point for launching an IPython kernel.


In [53]:
r

array([[8, 9, 7, 0],
       [3, 9, 2, 6],
       [1, 0, 9, 3]])

In [54]:
r[0], r[1], r[:,0] # retrieve rows and columns

(array([8, 9, 7, 0]), array([3, 9, 2, 6]), array([8, 3, 1]))

In [55]:
r[0:2]

array([[8, 9, 7, 0],
       [3, 9, 2, 6]])

In [56]:
r[1][2] # regular python

2

In [57]:
r[1, 2] # numpy

2

In [58]:
r[:, 1:3]

array([[9, 7],
       [9, 2],
       [0, 9]])

In [59]:
r > 5

array([[ True,  True,  True, False],
       [False,  True, False,  True],
       [False, False,  True, False]], dtype=bool)

In [60]:
r[r > 5]

array([8, 9, 7, 9, 6, 9])

In [61]:
r[r > 5] = 999

In [62]:
r

array([[999, 999, 999,   0],
       [  3, 999,   2, 999],
       [  1,   0, 999,   3]])